server:
  port: 8080
  servlet:
    context-path: /tzatziki-example

spring:
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy
  datasource:
    db: my_database
    host: localhost
    port: 5432
    default-schema: my_schema
    url: "jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db}?currentSchema=${spring.datasource.default-schema}"
    username: postgres
    password: postgres
  flyway:
    schemas: ${spring.datasource.default-schema}
